// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libqmomdrv_path=get_file_path('loader.sce');
link(libqmomdrv_path+'/libqmomdrv.so');
functions=[ 'qmom';
];
addinter(libqmomdrv_path+'/libqmomdrv.so','libqmomdrv',functions);
